name: CI 

on: 
  pull_request:
    branches:
      - release

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./posting-service-tests
      - name: Build
        run: dotnet build
        working-directory: ./posting-service-tests
      - name: Test with the dotnet CLI
        run: dotnet test
        working-directory: ./posting-service-tests
        
          
                  
    
