name: Docker CD

on:
  pull_request:
    branches:
      - Main
  
jobs:
  Build_and_deploy:
    runs-on: self-hosted
    steps:  
      - uses: actions/checkout@v3
      - name: Rebuild posting service
        run: |
          docker login --username coen-donk --password ${{ secrets.PACKAGE_SECRET }} ghcr.io
          docker build ./. --tag ghcr.io/coen-donk/posting-service:latest
          docker push ghcr.io/coen-donk/posting-service:latest
          docker stop posting-service
          docker remove posting-service
          docker run -d --name posting-service -p 8080:80 --network proxynetwork ghcr.io/coen-donk/posting-service:latest
          
